kind: pipeline
name: mailshield-build

steps:
  # 1. Main-Branch -> :latest
  - name: publish-latest
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: ghcr.io
      repo: rondevhub/mailshield # Kleingeschrieben!
      username:
        from_secret: ghcr_user
      password:
        from_secret: ghcr_token
      tags: latest
      dockerfile: Dockerfile
      context: .
    when:
      branch: main
      event: push

  # 2. Beta-Branch -> :beta (Wird bei jedem Push auf Beta gebaut)
  - name: publish-beta
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: ghcr.io
      repo: rondevhub/mailshield
      username:
        from_secret: ghcr_user
      password:
        from_secret: ghcr_token
      tags: beta
      dockerfile: Dockerfile
      context: .
    when:
      branch: beta
      event: [push, manual] # Manual allein ist oft zickig

  # 3. Release-Tags -> :v1.0.0
  - name: publish-tag
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: ghcr.io
      repo: rondevhub/mailshield
      username:
        from_secret: ghcr_user
      password:
        from_secret: ghcr_token
      tags: ${CI_COMMIT_TAG}
      dockerfile: Dockerfile
      context: .
    when:
      event: tag